### ISSUE TITLE
Files and configuration must be provided as arguments

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/device-detection-examples-go#20]
The Go performance example does [not enable](https://github.com/51Degrees/device-detection-examples-go/blob/c9a8d8f3c2397c130a02f6658a893f4862c20779/dd/performance/performance.go#L257) the settings and data files to be provided via the command line.

See the [C example](https://github.com/51Degrees/device-detection-cxx/blob/630361aba14a773dac7ee4d9309217714b2e5541/examples/C/Hash/Performance.c#L639) as the template.

**Comment by justadreamer** [comment]
done as part of #32
